import type {
  BoxStyle,
  ImageStyle,
  LayoutStyle,
  ShapeStyle,
  SlideRootFlowStyle,
  SlideStyle,
  TableCellStyle,
  TableRowStyle,
  TableSectionStyle,
  TableStyle,
  TextRunStyle,
  TextStyle,
  VideoStyle,
  ViewStyle,
} from "./types";

// Runtime key sets used by diagnostics and projection. They are checked against the public authored
// style groups but are not themselves public authoring types.
export const LAYOUT_STYLE_KEYS = [
  "opacity",
  "transform",
  "transformOrigin",
  "filter",
  "mixBlendMode",
  "isolation",
  "zIndex",
  "overflow",
  "alignSelf",
  "justifySelf",
  "placeSelf",
  "position",
  "order",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "gridArea",
  "gridColumnStart",
  "gridColumnEnd",
  "gridRowStart",
  "gridRowEnd",
  "gridColumn",
  "gridRow",
  "display",
  "visibility",
  "inset",
  "left",
  "top",
  "right",
  "bottom",
  "width",
  "height",
  "aspectRatio",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
] as const satisfies readonly (keyof LayoutStyle)[];

export const BOX_STYLE_KEYS = [
  "boxSizing",
  "background",
  "backgroundImage",
  "backgroundColor",
  "backgroundPosition",
  "backgroundSize",
  "backgroundRepeat",
  "backgroundClip",
  "backgroundOrigin",
  "boxShadow",
  "border",
  "borderColor",
  "borderWidth",
  "borderStyle",
  "borderTop",
  "borderRight",
  "borderBottom",
  "borderLeft",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "borderTopStyle",
  "borderRightStyle",
  "borderBottomStyle",
  "borderLeftStyle",
  "borderRadius",
  "outline",
  "outlineColor",
  "outlineWidth",
  "outlineStyle",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
] as const satisfies readonly (keyof BoxStyle)[];

export const FLOW_STYLE_KEYS = [
  "display",
  "flexDirection",
  "gap",
  "rowGap",
  "columnGap",
  "padding",
  "alignItems",
  "justifyContent",
  "justifyItems",
  "placeItems",
  "alignContent",
  "placeContent",
  "flexWrap",
  "gridTemplateAreas",
  "gridTemplateColumns",
  "gridTemplateRows",
  "gridAutoColumns",
  "gridAutoRows",
  "gridAutoFlow",
] as const satisfies readonly (keyof SlideRootFlowStyle)[];

export const VIEW_STYLE_KEYS = [
  ...LAYOUT_STYLE_KEYS,
  ...BOX_STYLE_KEYS,
  ...FLOW_STYLE_KEYS,
] as const satisfies readonly (keyof ViewStyle)[];

export const SLIDE_FLOW_STYLE_KEYS = FLOW_STYLE_KEYS;

export const SLIDE_STYLE_KEYS = [
  ...SLIDE_FLOW_STYLE_KEYS,
  "background",
  "backgroundImage",
  "backgroundColor",
  "backgroundPosition",
  "backgroundSize",
  "backgroundRepeat",
  "backgroundClip",
  "backgroundOrigin",
] as const satisfies readonly (keyof SlideStyle)[];

export const TEXT_STYLE_KEYS = [
  ...LAYOUT_STYLE_KEYS,
  ...BOX_STYLE_KEYS,
  "fontFamily",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "textDecoration",
  "textDecorationLine",
  "textDecorationStyle",
  "textDecorationColor",
  "textTransform",
  "direction",
  "writingMode",
  "color",
  "textAlign",
  "verticalAlign",
  "padding",
  "lineHeight",
  "paragraphSpacingBefore",
  "paragraphSpacingAfter",
  "textIndent",
  "tabStops",
  "letterSpacing",
  "whiteSpace",
  "wordBreak",
  "overflowWrap",
  "href",
  "tooltip",
  "listStyleType",
  "listStart",
  "listIndent",
  "superscript",
  "subscript",
  "textShadow",
  "fit",
] as const satisfies readonly (keyof TextStyle)[];

export const TABLE_STYLE_KEYS = [
  ...VIEW_STYLE_KEYS,
  "tableLayout",
  "borderCollapse",
] as const satisfies readonly (keyof TableStyle)[];

export const TABLE_SECTION_STYLE_KEYS =
  VIEW_STYLE_KEYS satisfies readonly (keyof TableSectionStyle)[];

export const TABLE_ROW_STYLE_KEYS = VIEW_STYLE_KEYS satisfies readonly (keyof TableRowStyle)[];

export const TABLE_CELL_STYLE_KEYS = TEXT_STYLE_KEYS satisfies readonly (keyof TableCellStyle)[];

export const TEXT_RUN_STYLE_KEYS = [
  "fontFamily",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "textDecoration",
  "textDecorationLine",
  "textDecorationStyle",
  "textDecorationColor",
  "textTransform",
  "direction",
  "writingMode",
  "color",
  "verticalAlign",
  "letterSpacing",
  "href",
  "tooltip",
  "superscript",
  "subscript",
  "textShadow",
] as const satisfies readonly (keyof TextRunStyle)[];

export const IMAGE_STYLE_KEYS = [
  "opacity",
  "transform",
  "transformOrigin",
  "filter",
  "mixBlendMode",
  "isolation",
  "zIndex",
  "overflow",
  "alignSelf",
  "justifySelf",
  "placeSelf",
  "position",
  "order",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "gridArea",
  "gridColumnStart",
  "gridColumnEnd",
  "gridRowStart",
  "gridRowEnd",
  "gridColumn",
  "gridRow",
  "display",
  "visibility",
  "inset",
  "left",
  "top",
  "right",
  "bottom",
  "width",
  "height",
  "aspectRatio",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
  "objectFit",
  "objectPosition",
  "crop",
  "href",
  "tooltip",
  "borderRadius",
  "boxShadow",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
] as const satisfies readonly (keyof ImageStyle)[];

export const VIDEO_STYLE_KEYS = [
  "opacity",
  "transform",
  "transformOrigin",
  "filter",
  "mixBlendMode",
  "isolation",
  "zIndex",
  "overflow",
  "alignSelf",
  "justifySelf",
  "placeSelf",
  "position",
  "order",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "gridArea",
  "gridColumnStart",
  "gridColumnEnd",
  "gridRowStart",
  "gridRowEnd",
  "gridColumn",
  "gridRow",
  "display",
  "visibility",
  "inset",
  "left",
  "top",
  "right",
  "bottom",
  "width",
  "height",
  "aspectRatio",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
  "objectFit",
  "objectPosition",
  "borderRadius",
  "boxShadow",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
] as const satisfies readonly (keyof VideoStyle)[];

export const SHAPE_STYLE_KEYS = [
  ...LAYOUT_STYLE_KEYS,
  ...BOX_STYLE_KEYS,
  "href",
  "tooltip",
  "fill",
  "stroke",
  "strokeDasharray",
  "strokeLinecap",
  "strokeLinejoin",
  "borderRadius",
] as const satisfies readonly (keyof ShapeStyle)[];
