export type {
  ClassNameObject,
  ClassNameValue,
  ClassNameValueArray,
  DataUriString,
  ImageSourceString,
  ImageNodeProps,
  ShapeNodeProps,
  SlideNodeProps,
  TableCellNodeProps,
  TableNodeProps,
  TableRowNodeProps,
  TableSectionNodeProps,
  TextNodeProps,
  TextRunNodeProps,
  VideoSourceString,
  VideoNodeProps,
  ViewNodeProps,
} from "./props";
export type { ShapeName, TableCellSpan } from "./contract";
export type {
  BorderStyle,
  BorderWidthValue,
  CssAlignContent,
  CssAlignItems,
  CssAlignSelf,
  CssAspectRatio,
  CssBoxSizing,
  CssBorderWidth,
  CssDisplay,
  CssBorderCollapse,
  CssFlexBasis,
  CssFlexDirection,
  CssFlexFactor,
  CssFlexWrap,
  CssFontWeight,
  CssGridAreaAuthoringString,
  CssGridAutoFlow,
  CssGridLine,
  CssGridPlacement,
  CssGridTemplate,
  CssGridTemplateAreas,
  CssGridTrack,
  CssInteger,
  CssJustifyContent,
  CssJustifySelf,
  CssLetterSpacing,
  CssObjectPosition,
  CssOverflow,
  CssPointLength,
  CssPosition,
  CssTableLayout,
  CssVisibility,
  DeckLength,
  DeckPointLength,
  ImageCropAuthoring,
  ImageCropValue,
  ImageStyle,
  ListStart,
  NonNegativeDeckLength,
  NonNegativeDeckLengthString,
  NonNegativeDeckPointLength,
  NonNegativeDeckPointLengthString,
  NonNegativeSpacing,
  ShapeStyle,
  SlideStyle,
  Spacing,
  StyleForAuthoredTag,
  StrokeDashType,
  StrokeLineCap,
  StrokeLineJoin,
  TableCellStyle,
  TableRowStyle,
  TableSectionStyle,
  TableStyle,
  TextFit,
  TextRunStyle,
  TextStyle,
  TextTabStopAlignment,
  TextTabStopAuthoring,
  TextTabStopLength,
  TooltipText,
  VerticalAlign,
  VideoStyle,
  ViewStyle,
} from "../style/types";
export type { DeckOptions } from "./options/public";
export type {
  AuthoringJsxNode,
  DeckJsxElement,
  DeckJsxElementValue,
  JsxNode,
  JsxNodeArray,
} from "./jsx-types";
export type { AuthoringExtensionValue } from "./extensions";
export type {
  ContentJsxChild,
  ContentJsxChildArray,
  ContentJsxElement,
  DeckJsxIntrinsicElements,
  ImageProps,
  IntrinsicDivProps,
  IntrinsicImgProps,
  IntrinsicPProps,
  IntrinsicShapeProps,
  IntrinsicSpanProps,
  IntrinsicTableCellProps,
  IntrinsicTableProps,
  IntrinsicTableRowProps,
  IntrinsicTableSectionProps,
  IntrinsicTableTag,
  IntrinsicTextTag,
  IntrinsicVideoProps,
  IntrinsicViewTag,
  ShapeProps,
  SlideProps,
  TableCellJsxChild,
  TableCellJsxChildArray,
  TableJsxChild,
  TableJsxChildArray,
  TableRowJsxChild,
  TableRowJsxChildArray,
  TableSectionJsxChild,
  TableSectionJsxChildArray,
  TextJsxChild,
  TextJsxChildArray,
  TextProps,
  VideoProps,
  ViewIntrinsicJsxChild,
  ViewIntrinsicJsxChildArray,
  ViewProps,
} from "./intrinsic";
export type { StyleClassStyle, StyleSheetValue } from "../style/stylesheet";

export type SlideContext = {
  composition: import("../composition/public").CompositionContext;
};

export type SlideFactory<TSourceContext = void> =
  import("../composition/public").SlideFactory<TSourceContext>;
