export { pptxgenjsBackend } from "./backends/pptxgenjs";
export type {
  BackgroundImageLayerIR,
  BackgroundLayerIR,
  BackendArtifact,
  BaseNodeIR,
  CompileBackend,
  EdgeStrokeIR,
  FillIR,
  FrameIR,
  GroupIR,
  HyperlinkIR,
  ImageCropIR,
  ImageIR,
  ImageSourceIR,
  LinearGradientFillIR,
  LinearGradientStopIR,
  NodeIR,
  ObjectPositionIR,
  PresentationIR,
  RadialGradientFillIR,
  ShadowIR,
  ShapeIR,
  SizeIR,
  SlideIR,
  SolidFillIR,
  StrokeIR,
  TextContentIR,
  TextIR,
  TextListIR,
  TextNumberListIR,
  TextNoListIR,
  TextBulletListIR,
  TextRunIR,
  TextStyleIR,
  TextTabStopIR,
} from "./ir/index";
