export const EMU_PER_INCH = 914_400;
export const POINTS_PER_INCH = 72;
export const PIXELS_PER_INCH = 96;

export type {
  AuthorNode,
  AuthorNodeKind,
  AuthorNodeMap,
  BackendName,
  BorderStyle,
  ClassNameObject,
  ClassNameValue,
  ClassNameValueArray,
  ContentAuthorNode,
  ContentJsxChild,
  CssAlignContent,
  CssAlignItems,
  CssAlignSelf,
  CssAspectRatio,
  CssBoxSizing,
  CssDisplay,
  CssFlexBasis,
  CssFlexDirection,
  CssFlexWrap,
  CssGridAutoFlow,
  CssGridLine,
  CssGridPlacement,
  CssGridShorthand,
  CssGridTemplate,
  CssGridTemplateAreas,
  CssGridTemplateShorthand,
  CssGridTrack,
  CssJustifyContent,
  CssJustifySelf,
  CssObjectPosition,
  CssOverflow,
  CssPosition,
  CssVisibility,
  DeckLength,
  DeckOptions,
  DeckPointLength,
  DeckJsxIntrinsicElements,
  ImageCropAuthoring,
  ImageCropValue,
  ImageProps,
  ImageStyle,
  IntrinsicDivProps,
  IntrinsicImgProps,
  IntrinsicPProps,
  IntrinsicTextTag,
  IntrinsicViewTag,
  ImplementedBackendName,
  JsxNode,
  LayoutMode,
  OutputConfig,
  ShapeProps,
  ShapeStyle,
  SlideProps,
  SlideStyle,
  Spacing,
  StackAlignment,
  StackAxis,
  StrokeDashType,
  StrokeLineCap,
  StrokeLineJoin,
  TextFit,
  TextProps,
  TextStyle,
  TextJsxChild,
  TextTabStopAlignment,
  TextTabStopAuthoring,
  TextTabStopLength,
  VerticalAlign,
  ViewProps,
  ViewStyle,
} from "./authoring/index";
export type {
  BoundSource,
  CompositionContext,
  SlideFactory,
  SlideFactoryInput,
  SourceContextMapper,
} from "./deck";

export type {
  AssetEntity,
  AssetEntityId,
  BaseSemanticNode,
  GraphNodeId,
  SemanticAuthorGraph,
  SemanticContainerNode,
  SemanticDocumentNode,
  SemanticImageNode,
  SemanticNode,
  SemanticNodeKind,
  SemanticOrigin,
  SemanticRole,
  SemanticShapeNode,
  SemanticSlideNode,
  SemanticTextNode,
  SemanticTextRunNode,
  SourceIdentity,
  SourceOrigin,
  StyleClassRef,
  StyleEntity,
  StyleEntityId,
} from "./graph";

export type {
  BackgroundImageLayerIR,
  BackgroundLayerIR,
  BackendArtifact,
  BaseNodeIR,
  CompileBackend,
  EdgeStrokeIR,
  FillIR,
  FrameIR,
  GroupIR,
  HyperlinkIR,
  ImageCropIR,
  ImageIR,
  ImageSourceIR,
  LinearGradientFillIR,
  LinearGradientStopIR,
  NodeIR,
  ObjectPositionIR,
  PresentationIR,
  RadialGradientFillIR,
  ShadowIR,
  ShapeIR,
  SizeIR,
  SlideIR,
  SolidFillIR,
  StrokeIR,
  TextContentIR,
  TextIR,
  TextBulletListIR,
  TextListIR,
  TextNoListIR,
  TextNumberListIR,
  TextRunIR,
  TextStyleIR,
  TextTabStopIR,
} from "./ir/index";
